language: c++

install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl
  - haxelib install openfl-tools
  - haxelib install hxcpp
  - haxelib git nme https://github.com/haxenme/NME
  - haxelib git nmedev https://github.com/haxenme/nmedev
  - haxelib install munit
  - haxelib install format
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl-native $(pwd)
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x32 -extension GLX"
  - "export AUDIODEV=null"

script:
  - haxelib run openfl rebuild linux
  - haxelib run openfl test ~/openfl-validation linux
  #- haxelib run openfl test ~/openfl-validation neko
